src/main/java/sun/naitei/group3/movie_ticket_booking_system/dto/response/BaseApiResponse.java, src/main/java/sun/naitei/group3/movie_ticket_booking_system/exception/AuthenticationFailedEx.java, src/main/java/sun/naitei/group3/movie_ticket_booking_system/exception/GlobalExceptionHandler.java
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/90773)
- config exception
- Tạo class ErrorResponse - đại diện cho response khi có lỗi
- config exception với @RestControllerAdvice 
- Bắt lỗi cụ thể xảy ra trong quá trình xử lý HTTP request
- Trả về thông báo lỗi cụ thể, dễ đọc
thông báo ex trả về sẽ có dạng:
```json
{
"timestamp": "2025-08-04T12:54:39.4887581+07:00",
"status": 400,
"error": "Bad Request",
"message": "Validation Failed",
"validationErrors": {
"name": "Tên không được để trống",
"email": "Email không hợp lệ"
},
"path": "/api/users"
}
```
=> Refs [Task] [90773] [config handler exception]

pom.xml, src/main/java/sun/naitei/group3/movie_ticket_booking_system/config/OpenApiConfig.java, src/main/java/sun/naitei/group3/movie_ticket_booking_system/config/SecurityConfig.java
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91049)
- config swagger ui
- cài đặt thư viện springdoc-openapi-starter-webmvc-ui
- config trong file OpenApiConfig
- Tài liệu cho RESTful Api
=> init swagger

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/ShowtimeController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/converter/ConvertToDtos.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/ShowtimeFilterReq.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/ShowtimeDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/enums/BookingStatus.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/enums/ShowtimeStatus.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/BookingSeatRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/ShowtimeRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/ShowtimeService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/ShowtimeServiceImpl.java, src/main/resources/application.properties.example, src/main/resources/messages.properties, src/main/resources/templates/admin/showtimes/index.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91278)
- Hiển thị danh sách xuất chiếu, có bộ lọc, phân trang
- Sử dụng Spring Boot kết hợp với Spring Data JPA và câu lệnh @query để lọc dữ liệu từ cơ sở dữ liệu.
- Trên giao diện admin, sử dụng table-striped để hiển thị danh sách xuất chiếu, kết hợp thanh tìm kiếm và bộ lọc.
- Áp dụng phân trang (pagination) để tránh tải toàn bộ dữ liệu một lần.
- Hỗ chợ feature quản lý xuất chiếu
=> Refs [Task] [91278] [Màn hình danh sách xuất chiếu]

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/MovieController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/MovieController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/MovieRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/MovieService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/MovieServiceImpl.java, src/main/resources/messages.properties
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91686)
- search phim đang được chiếu
- thêm api /api/v1/movies/now-showing
- query lấy ra những phim nào có tồn tại trong danh sách showtimes và có status là available (0)
Nếu không có phim nào đang chiếu:
=> [91686] [api] [customer] search phim đang được chiếu

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/CinemaController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/HallDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/CinemaRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/GenreRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/HallRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/MovieRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/RoleRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/UserRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/CinemaService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/HallService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/CinemaServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/HallServiceImpl.java, src/main/resources/messages.properties, src/main/resources/templates/admin/cinemas/detail.html, src/main/resources/templates/admin/cinemas/index.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91275)
- Hiển thị thông tin chi tiết của rạp khi ấn vào rạp trên màn hình danh sách rạp.
- Thêm danh sách các phòng chiếu của rạp, hiển thị tên phòng và tổng số ghế.
- Thymeleaf hiển thị box chi tiết rạp với các thông tin cơ bản (tên, địa chỉ, thành phố, bản đồ).
- Dưới box rạp, sử dụng vòng lặp th:each để hiển thị các phòng chiếu, mỗi phòng có tên, tổng số ghế và nút xem chi tiết.
-Giúp admin dễ dàng kiểm tra chi tiết từng rạp và các phòng chiếu của rạp.
=> Refs [Task][91275]Feat[admin]: View cinema details

src/main/java/com/naitei/group3/movie_ticket_booking_system/config/SecurityConfig.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/AuthController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/HomeController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/AuthController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/GlobalExceptionHandler.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/PermissionRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/UserRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/security/CustomUserPrincipal.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/security/MyUserDetailsServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/UserService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/UserServiceImpl.java, src/main/resources/messages.properties, src/main/resources/static/js/register.js, src/main/resources/templates/admin/register.html, src/main/resources/templates/errors/error_without-layout.html
done test
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/90919)
- Sử dụng basic auth đăng nhập hệ thống
- có xác thực Role
- security config
- UserDetailsService
Với trang admin:
với api:
=> [90919] Task login/xác thực/phân quyền sử dụng Basic Auth của Spring security

src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/ShowtimeRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/MovieServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/ShowtimeServiceImpl.java
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/???)
- Change number items `completed/total` in admin page.
- I edit js file, inject not_vary_normal items in calculate function.
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.
=> fix use enum

src/main/java/com/naitei/group3/movie_ticket_booking_system/MovieTicketBookingSystemApplication.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/BookingController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/BookingRequestDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/BookingDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/entity/Booking.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/NotEnoughPointsException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/SeatAlreadyBookedException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/BookingRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/BookingSeatRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/SeatRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/BookingService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/UserPointService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/BookingServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/UserPointServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/utils/BookingCleanupTask.java
Api booking
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/???)
- tính năng booking ticket người dùng
- logic người dùng truyền vào : thông tin user , suốt chiếu , ghế  đã chọn , số điểm sử dụng để được giảm giá . 
- Giảm giá được trừ vào tổng số tiền của booking
- hệ thống sau đó sẽ lưu booking vào trạng thái pending . sau 10 phút vẫn trong trạng thái chờ tự động huỷ , nếu booking  bị huỷ người dùng sẽ không được hoàn điểm 
- Gồm tổng cộng 2api : để tạo booking và tra cứu booking thông tin booking (chi tiết ở tronng ảnh cap màn hình)
- Tạo file code liên quan booking gồm controller , service , reposistory, DTO tương ứng . 
- Phải kiểm tra …
=> [ Task][91690] [Customer ] [Booking ]

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/MovieController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/MovieSearchApiRequest.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/MovieRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/MovieService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/MovieServiceImpl.java
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91684)
- Api search phim cho user. Có thể search theo keyword tên phim, mô tả phim hoặc thể loại. Có thể lọc theo ngày chiếu.
- thêm api /api/v1/movies/search
- query lấy ra những phim theo filter. keyword có thể search với tên phim và mô tả phim
Không truyền gì sẽ ra tất cả:
truyền đẩy đủ 3 giá trị:
Truyền 2 giá trị:
truyền 1 giá trị và tìm kiếm với mô tả:
=> [91684] [api customer] search phim cho api customer

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/RevenueController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/RevenueDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/entity/PaymentTransaction.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/enums/PaymentStatus.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/PaymentTransactionRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/projection/RevenueProjection.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/RevenueService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/RevenueServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/utils/RevenueLabelFormatter.java, src/main/resources/messages.properties, src/main/resources/static/js/revenues.js, src/main/resources/templates/_fragments/_head.html, src/main/resources/templates/_fragments/_sidebar.html, src/main/resources/templates/admin/revenues/index.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91698)
- Hiển thị số liệu thống kê doanh thu và giao dịch (tổng doanh thu, số giao dịch thành công, đang chờ và thất bại) trên trang quản trị.
- Xem được doanh thu theo ngày/tháng/năm
- Lấy query theo các status (enums) để đưa ra số lượng của các giao dịch 
- Lấy query theo ngày hoặc tháng hoặc năm để đưa doanh thu theo từng loại với chart.js hiển thị
- Trang hiển thị số liệu theo từng trạng thái (thành công, chờ xử lý, thất bại) giúp admin dễ dàng theo dõi tình hình kinh doanh và đưa ra quyết định nhanh hơn.
=> Refs [Task][91698]: Feat(Admin): View revenues page

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/HallController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/converter/DtoConverter.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/HallRequestDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/GlobalExceptionHandler.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/HallAlreadyExistsException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/HallRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/HallService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/HallServiceImpl.java, src/main/resources/messages.properties, src/main/resources/templates/admin/cinemas/detail.html, src/main/resources/templates/admin/cinemas/halls/add.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/92139)
- Thêm phòng chiếu vào rạp phim có sẵn.
- Ấn vào giao diện thêm, điền tên phòng và tổng số ghế.
=> [Subtask][92139] [Manager][Thêm phòng chiếu]

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/PaymentController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/PaymentResponseDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/PaymentResultDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/entity/PaymentTransaction.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/enums/PaymentStatus.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/InvalidSignatureException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/PaymentException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/PaymentFailedException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/BookingRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/PaymentTransactionRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/PaymentGateway.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/VnPayServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/utils/VnPayUtils.java, src/main/resources/application.properties.example
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91691)
---
**Controller Layer**
* Thêm `PaymentController` với 3 API:
* `POST /api/v1/pay/create` → tạo URL thanh toán VNPAY cho booking.
* `GET /api/v1/pay/return` → xử lý redirect từ VNPAY (return URL).
* `POST /api/v1/pay/ipn` → xử lý callback từ VNPAY (IPN) để cập nhật trạng thái thanh toán và booking.
**Service Layer**
* Cài đặt `PaymentGateway` qua `VnPayServiceImpl`.
* Chức năng:
* Sinh URL thanh toán VNPAY kèm chữ ký bảo mật.
* Xác thực phản hồi từ VNPAY.
* Ghi nhận giao dịch (`PaymentTransaction`) vào DB.
* Cập nhật trạng thái booking sang **PAID** khi thanh toán thành công …
=> [Task] [91691 ] [Customer] [api payment ]

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/CinemaController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/CinemaController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/CinemaDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/CinemaRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/CinemaService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/MovieService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/CinemaServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/MovieServiceImpl.java, src/main/resources/messages.properties
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91687)
- Danh sách rạp đang chiếu phim được chọn 
- Thêm MovieController cho rest api.
- Query tìm danh sách rạp dựa trên movie_id và showtimes đang chiếu movie đó 
- Hỗ trợ api booking (user xem và chọn rạp muốn đặt)
**Danh sách xuất chiếu hiện có:**
**test api:**
=> [91687] [api customer] get cinema by movie

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/BookingController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/BookingService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/UserPointService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/BookingServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/UserPointServiceImpl.java
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/92040)
---
* Triển khai API hủy booking: `PATCH /bookings/{id}/cancel`.
* Cập nhật trạng thái booking thành `CANCELED` thay vì xóa bản ghi.
* API trả về mã và thông điệp phù hợp.
* Chuyển method trong `BookingController` từ `@DeleteMapping` sang `@PatchMapping`.
* Gọi `bookingService.cancelBooking()` để cập nhật trạng thái trong database (soft-delete).
* Giữ lại bản ghi booking trong database để theo dõi lịch sử và báo cáo.
* Tuân theo chuẩn REST: `PATCH` phù hợp hơn để **cập nhật một phần tài nguyên** so với `DELETE`.
* Giữ lịch sử booking cho mục đích báo cáo, phân tích hoặc hoàn tiền.
* …
=> [Task][92040][Customer][Cancel Booking]

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/MovieController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/MovieDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/MovieService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/MovieServiceImpl.java, src/main/resources/application.properties.example, src/main/resources/messages.properties, src/main/resources/static/css/genre.css, src/main/resources/static/js/genre.js, src/main/resources/templates/_fragments/_head.html, src/main/resources/templates/admin/movies/update.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/?90929)
- Cập nhật thông tin của phim.
- Tìm phim theo id, sửa thông tin và lưu vào database
- Giúp admin cập nhật thông tin mới nhất về phim
=> [Task][90929] [Manager] [Cập nhật thông tin phim]

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/AuthController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/UserController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/ChangePasswordRequest.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/ForgotPasswordRequest.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/entity/VerificationToken.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/GlobalExceptionHandler.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/InvalidOldPasswordException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/UserNotVerifiedException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/EmailService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/PasswordService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/EmailServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/PasswordServiceImpl.java, src/main/resources/application.properties.example, src/main/resources/messages.properties, src/main/resources/templates/email/reset-password-email_EN.html, src/main/resources/templates/email/reset-password-email_VI.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/90921)
- Đổi mật khẩu user
- Nếu còn nhớ mật khẩu cũ thì đổi trực tiếp được.
- Nếu quên mật khẩu sẽ gửi email xác minh.
- Hỗ trợ user đổi mật khẩu
=> [90921] change password

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/RatingController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/converter/DtoConverter.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/RatingDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/entity/Rating.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/RatingRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/RatingService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/RatingServiceImpl.java, src/main/resources/messages.properties, src/main/resources/templates/_fragments/_sidebar.html, src/main/resources/templates/admin/ratings/index.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/91695)
- Thêm mới trang quản lý đánh giá (ratings) trong trang admin.
- Hiển thị danh sách các đánh giá kèm trạng thái (PENDING, APPROVED, REJECTED).
- Cho phép admin duyệt / từ chối các đánh giá đang ở trạng thái chờ (PENDING).
- Lấy danh sách list các ratings theo status ở repository
- Sử dụng điều kiện lọc theo điều kiện
- Đảm bảo admin có thể kiểm soát chất lượng nội dung đánh giá do người dùng gửi.
- Giúp loại bỏ các đánh giá không phù hợp, chỉ giữ lại những đánh giá đã được phê duyệt.
-
=> Refs [Task][91695] Feat(admin): view ratings page

src/main/java/com/naitei/group3/movie_ticket_booking_system/config/AppConfig.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/HallController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/SeatController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/SeatEditRequest.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/SeatRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/SeatTypeRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/SeatService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/SeatTypeService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/SeatServiceImpl.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/SeatTypeServiceImpl.java, src/main/resources/messages.properties, src/main/resources/static/css/seats.css, src/main/resources/templates/admin/cinemas/halls/index.html, src/main/resources/templates/admin/cinemas/seats/edit.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/92229)
- Admin chỉnh sửa type của ghế
- Đưa ra list type của ghế để admin chọn lại cho ghế
- Button chỉnh sửa trên mỗi ghế để đưa tới trang sửa ghế theo id
-Thay đổi type của ghế theo ý muốn
=> [Task][92229]Feat(Admin): Edit seat of hall (just type of seat)

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/CinemaRecommendationController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/LocationController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/CinemaRecommendationDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/InvalidMapUrlException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/RatingRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/ShowtimeRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/CinemaRecommendationService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/CinemaRecommendationServiceImpl.java, src/main/resources/templates/location/getLocation.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/92039)
---
**WHAT (optional)**
Triển khai API gợi ý rạp chiếu phim gần vị trí hiện tại của người dùng:
* Lấy danh sách rạp trong bán kính nhất định từ tọa độ người dùng.
* Chỉ trả về rạp còn phim chiếu sau thời điểm hiện tại.
* Tính khoảng cách từ người dùng đến rạp dựa trên toạ độ hiện tại lấy của User và cinemas `mapUrl` và trả về thông tin rạp kèm danh sách phim.
**HOW**
* Dùng HTML5 Geolocation API để lấy tọa độ từ frontend. Người dùng phải tương tác trực tiếp FE để lấy toạ độ . 
* Sử dụng `GET /api/recommendations/nearby-cinemas?latitude={lat}&longitude={lon}&radiusKm={radius}` với tạo độ …
=> [Task] [92039] [System] [Recomedation cinemas by user location]

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/RatingController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/GlobalExceptionHandler.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/exception/RatingNotFoundException.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/RatingService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/RatingServiceImpl.java, src/main/resources/messages.properties, src/main/resources/templates/admin/ratings/index.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/92204)
- Thêm chức năng cho admin có thể xét duyệt (duyệt hoặc từ chối) các đánh giá mà user gửi lên.
- Tạo các API/controller xử lý duyệt hoặc từ chối đánh giá.
- Thêm xác nhận trước khi thực hiện.
- Đảm bảo chỉ những đánh giá hợp lệ, phù hợp nội dung mới được công khai.
=> [Task][92204]Feat(Admin): Moderate user ratings - Xét duyệt đánh giá của user

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/api/UserController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/UserUpdateRequest.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/response/UserDTO.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/UserService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/UserServiceImpl.java, src/main/resources/messages.properties
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/90923)
- Chỉnh sửa thông tin user.
- thêm 2 api get và put ở /api/v1/users/me
- có validate giá trị
- Hỗ trợ chức năng chỉnh sửa thông tin user
=> [90923] [api customer] edit user info

src/main/java/com/naitei/group3/movie_ticket_booking_system/controller/admin/SeatController.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/dto/request/AddSeatRequest.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/entity/Hall.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/repository/SeatRepository.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/SeatService.java, src/main/java/com/naitei/group3/movie_ticket_booking_system/service/impl/SeatServiceImpl.java, src/main/resources/messages.properties, src/main/resources/templates/admin/cinemas/halls/index.html, src/main/resources/templates/admin/cinemas/seats/add.html
---
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/92140)
- Chuẩn hoá row thành in hoa trước khi xử lý.
- Hỗ trợ cả trường hợp nhập row chữ thường hoặc chữ hoa (tự động chuyển thành in hoa)
- Chuẩn hoá row thành in hoa trước khi xử lý.
- Lấy ra số ghế tối đa đã có trong row để tính tiếp số ghế cần thêm. (số ghế được thêm không vượt quá số ghế max trong 1 hàng)
- Sinh ra các ghế mới với seatRow, seatColumn, seatType, rồi lưu vào DB.
- Admin có thể thêm ghế theo ý muốn
=> [Task][92140]Feat(admin): Add seats
